=== andrejumeahu/my-otsdaq-demo/Data/ConfigurationDataExamples/ConfigurationBase.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="ROOT">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="HEADER">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="TYPE">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="EXTENSION_TABLE_NAME" type="xs:string"/>
                  <xs:element name="NAME" type="xs:string"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="RUN">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="RUN_TYPE" type="xs:string"/>
                  <xs:element name="RUN_NUMBER" type="xs:string"/>
                  <xs:element name="RUN_BEGIN_TIMESTAMP" type="xs:string"/>
                  <xs:element name="LOCATION" type="xs:string"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="DATA_SET">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="PART">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="NAME_LABEL" type="xs:string"/>
                  <xs:element name="KIND_OF_PART" type="xs:string"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="VERSION" type="xs:string"/>
            <xs:element name="COMMENT_DESCRIPTION" type="xs:string"/>
            <xs:element name="CREATED_BY_USER" type="xs:string"/>
            <xs:element name="DATA" minOccurs="1" maxOccurs="unbounded">
              <xs:complexType>
                <xs:sequence>
                  <xs:any minOccurs="1" maxOccurs="unbounded" processContents='skip'/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>
</xs:schema>

=== andrejumeahu/my-otsdaq-demo/Data/ConfigurationDataExamples/DataDecoderConsumerConfiguration/0/DataDecoderConsumerConfiguration_v0.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../ConfigurationBase.xsd">

 <HEADER>
  <TYPE>
   <EXTENSION_TABLE_NAME>DATA_DECODER_CONSUMER_CONFIGURATION</EXTENSION_TABLE_NAME>
   <NAME>DataDecoderConsumerConfiguration</NAME>
  </TYPE>
  <RUN>
   <RUN_TYPE>DataDecoderConsumerConfiguration</RUN_TYPE>
   <RUN_NUMBER>1</RUN_NUMBER>
   <RUN_BEGIN_TIMESTAMP>2013-01-29 17:22:10</RUN_BEGIN_TIMESTAMP>
   <LOCATION>CERN P5</LOCATION>
  </RUN>
 </HEADER>

  <DATA_SET>
 
   <PART>
    <NAME_LABEL>CMS--ROOT</NAME_LABEL>
    <KIND_OF_PART>Detector ROOT</KIND_OF_PART>
   </PART>
   <VERSION>0</VERSION>
   <COMMENT_DESCRIPTION></COMMENT_DESCRIPTION>
   <CREATED_BY_USER></CREATED_BY_USER>
  
   <DATA>
    <PROCESSOR_ID>DataDecoder0FER0</PROCESSOR_ID>
   </DATA>

   <!-- <DATA> -->
   <!--  <PROCESSOR_ID>ARTDAQDataDecoder0</PROCESSOR_ID> -->
   <!--  <FILE_PATH>/tmp</FILE_PATH> -->
   <!--  <RADIX_FILE_NAME>DataDecoder0FER0</RADIX_FILE_NAME> -->
   <!-- </DATA> -->

  
 </DATA_SET>
</ROOT>

=== andrejumeahu/my-otsdaq-demo/Data/ConfigurationDataExamples/DQMHistosConsumerConfiguration/1/DQMHistosConsumerConfiguration_v1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../ConfigurationBase.xsd">

 <HEADER>
  <TYPE>
   <EXTENSION_TABLE_NAME>DQM_HISTOS_CONSUMER_CONFIGURATION</EXTENSION_TABLE_NAME>
   <NAME>DQMHistosConsumerConfiguration</NAME>
  </TYPE>
  <RUN>
   <RUN_TYPE>DQMHistosConsumerConfiguration</RUN_TYPE>
   <RUN_NUMBER>1</RUN_NUMBER>
   <RUN_BEGIN_TIMESTAMP>2013-01-29 17:22:10</RUN_BEGIN_TIMESTAMP>
   <LOCATION>CERN P5</LOCATION>
  </RUN>
 </HEADER>

  <DATA_SET>
 
   <PART>
    <NAME_LABEL>CMS--ROOT</NAME_LABEL>
    <KIND_OF_PART>Detector ROOT</KIND_OF_PART>
   </PART>
   <VERSION>1</VERSION>
   <COMMENT_DESCRIPTION></COMMENT_DESCRIPTION>
   <CREATED_BY_USER></CREATED_BY_USER>

    <DATA> 
      <PROCESSOR_ID>DQMHistos0</PROCESSOR_ID>
      <FILE_PATH>/data/TestBeam/2016_06_June/OtsHistos/</FILE_PATH>
      <RADIX_FILE_NAME>DQMHistos0</RADIX_FILE_NAME>
      <SAVE_FILE>yes</SAVE_FILE>
    </DATA>

</DATA_SET>
</ROOT>

=== andrejumeahu/my-otsdaq-demo/Data/ConfigurationDataExamples/ARTDAQAggregatorConfiguration/1/ARTDAQAggregatorConfiguration_v1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../ConfigurationBase.xsd">

 <HEADER>
  <TYPE>
   <EXTENSION_TABLE_NAME>ARTDAQ_AGGREGATOR_CONFIGURATION</EXTENSION_TABLE_NAME>
   <NAME>ARTDAQAggregatorConfiguration</NAME>
  </TYPE>
  <RUN>
   <RUN_TYPE>ARTDAQAggregatorConfiguration</RUN_TYPE>
   <RUN_NUMBER>1</RUN_NUMBER>
   <RUN_BEGIN_TIMESTAMP>2013-01-29 17:22:10</RUN_BEGIN_TIMESTAMP>
   <LOCATION>CERN P5</LOCATION>
  </RUN>
 </HEADER>

  <DATA_SET>
 
   <PART>
    <NAME_LABEL>CMS--ROOT</NAME_LABEL>
    <KIND_OF_PART>Detector ROOT</KIND_OF_PART>
   </PART>
   <VERSION>1</VERSION>
   <COMMENT_DESCRIPTION></COMMENT_DESCRIPTION>
   <CREATED_BY_USER></CREATED_BY_USER>
  
   <DATA>
    <SUPERVISOR_INSTANCE>1</SUPERVISOR_INSTANCE>
    <AGGREGATOR_ID>1</AGGREGATOR_ID>
    <STATUS>on</STATUS>
    <CONFIGURATION_STRING>
		daq:
		{
			aggregator:
			{
				event_builder_count:1 
				event_queue_depth:20 
				event_queue_wait_time:5 
				expected_events_per_bunch:1 
				file_duration:0 
				file_event_count:0 
				file_size_MB:0 
				first_event_builder_rank:1 
				mpi_buffer_count:8 
				print_event_store_stats:true 
				xmlrpc_client_list:";http://localhost:5100/RPC2,3;http://localhost:5101/RPC2,3;http://localhost:5200/RPC2,4;http://localhost:5201/RPC2,4;http://localhost:5300/RPC2,5;http://localhost:5301/RPC2,5"
			} 
			max_fragment_size_words:2.097152e6
		} 
		outputs:
		{
			normalOutput:
			{
				fileName:"/tmp/artdaqots_r%06r_sr%02s_%to.root" 
				module_type:"RootOutput"
			}
		} 
		physics:
		{
			my_output_modules:["normalOutput"] 
			p2:["BuildInfo"] 
			a1:["wf"] 
			producers:
			{
				BuildInfo:
				{
					instance_name:"ArtdaqOts" 
					module_type:"ArtdaqOtsBuildInfo"
				}
			} 
			analyzers:
			{
				wf:
				{
					module_type:"WFViewer" 
					fragment_ids:[0] 
					fragment_type_labels:["STIB"] 
					prescale:60 
					write_to_file:true 
					fileName:"/tmp/otsdaqdemo_onmon.root"
				}
			}
		} 
		process_name:"DAQAG" 
		services:
		{
			Timing:
			{
				summaryOnly:true
			} 
			scheduler:
			{
				fileMode:"NOMERGE" 
				errorOnFailureToPut: false
			} 
			NetMonTransportServiceInterface:
			{
				max_fragment_size_words:2097152 
				service_provider:"NetMonTransportService"
			}
		} 
		source:
		{
			module_type:"NetMonInput"
		}
    </CONFIGURATION_STRING>
   </DATA>

  
 </DATA_SET>
</ROOT>

=== andrejumeahu/my-otsdaq-demo/Data/ConfigurationDataExamples/RawDataSaverConsumerConfiguration/1/RawDataSaverConsumerConfiguration_v1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../ConfigurationBase.xsd">

 <HEADER>
  <TYPE>
   <EXTENSION_TABLE_NAME>RAW_DATA_SAVER_CONSUMER_CONFIGURATION</EXTENSION_TABLE_NAME>
   <NAME>RawDataSaverConsumerConfiguration</NAME>
  </TYPE>
  <RUN>
   <RUN_TYPE>RawDataSaverConsumerConfiguration</RUN_TYPE>
   <RUN_NUMBER>1</RUN_NUMBER>
   <RUN_BEGIN_TIMESTAMP>2013-01-29 17:22:10</RUN_BEGIN_TIMESTAMP>
   <LOCATION>CERN P5</LOCATION>
  </RUN>
 </HEADER>

  <DATA_SET>
 
   <PART>
    <NAME_LABEL>CMS--ROOT</NAME_LABEL>
    <KIND_OF_PART>Detector ROOT</KIND_OF_PART>
   </PART>
   <VERSION>1</VERSION>
   <COMMENT_DESCRIPTION></COMMENT_DESCRIPTION>
   <CREATED_BY_USER></CREATED_BY_USER>
  
   <DATA>
    <PROCESSOR_ID>RawDataSaver0PurdueFE0</PROCESSOR_ID>
    <FILE_PATH>/tmp</FILE_PATH>
    <RADIX_FILE_NAME>RawDataSaver0PurdueFE0</RADIX_FILE_NAME>
   </DATA>
  
 </DATA_SET>
</ROOT>

=== andrejumeahu/my-otsdaq-demo/Data/ConfigurationDataExamples/ARTDAQBuilderConfiguration/1/ARTDAQBuilderConfiguration_v1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../ConfigurationBase.xsd">

 <HEADER>
  <TYPE>
   <EXTENSION_TABLE_NAME>ARTDAQ_BUILDER_CONFIGURATION</EXTENSION_TABLE_NAME>
   <NAME>ARTDAQBuilderConfiguration</NAME>
  </TYPE>
  <RUN>
   <RUN_TYPE>ARTDAQBuilderConfiguration</RUN_TYPE>
   <RUN_NUMBER>1</RUN_NUMBER>
   <RUN_BEGIN_TIMESTAMP>2013-01-29 17:22:10</RUN_BEGIN_TIMESTAMP>
   <LOCATION>CERN P5</LOCATION>
  </RUN>
 </HEADER>

  <DATA_SET>
 
   <PART>
    <NAME_LABEL>CMS--ROOT</NAME_LABEL>
    <KIND_OF_PART>Detector ROOT</KIND_OF_PART>
   </PART>
   <VERSION>1</VERSION>
   <COMMENT_DESCRIPTION></COMMENT_DESCRIPTION>
   <CREATED_BY_USER></CREATED_BY_USER>
  
   <DATA>
    <SUPERVISOR_INSTANCE>1</SUPERVISOR_INSTANCE>
    <BUILDER_ID>1</BUILDER_ID>
    <STATUS>on</STATUS>
    <CONFIGURATION_STRING>
    	daq:
    	{
    		event_builder:
    		{
    			expected_fragments_per_event:1 
    			first_fragment_receiver_rank:0 
    			fragment_receiver_count:1 
    			mpi_buffer_count:16 
    			print_event_store_stats:true 
    			send_triggers:true 
    			trigger_port:5001 
    			use_art:true 
    			verbose:false
    		} 
    		max_fragment_size_words:2.097152e6
    	} 
    	outputs:
    	{
    		netMonOutput:
    		{
    			module_type:"RootMPIOutput"
    		}
    	} 
    	physics:
    	{
    		analyzers:
    		{
    			wf:
    			{
    				module_type:"WFViewer" 
    				fragment_ids:[0] 
    				fragment_type_labels:["STIB"] 
    				prescale:60 
    				write_to_file:true 
    				fileName:"/tmp/otsdaqdemo_onmon_evb.root"
    			}
    		}  
    		a1:["wf"] 
    		my_output_modules:["netMonOutput"]
    	} 
    	process_name:"DAQ" 
    	services:
    	{
    		Timing:
    		{
    			summaryOnly:true
    		} 
    		scheduler:
    		{
    			fileMode:"NOMERGE" 
    			errorOnFailureToPut: false
    		} 
    		user:
    		{
    			NetMonTransportServiceInterface:
    			{
    				data_receiver_count:1 
    				first_data_receiver_rank:2 
    				max_fragment_size_words:2.097152e6 
    				mpi_buffer_count:8 
    				service_provider:"NetMonTransportService"
    			}
    		}
    	} 
    	source:
    	{
    		fragment_type_map:[[1,"UDP"], [4,"STIB"]] 
    		module_type:"RawInput" 
    		resume_after_timeout:true 
    		waiting_time:900
    	}    	
    </CONFIGURATION_STRING>
   </DATA>

  
 </DATA_SET>
</ROOT>
